version: "3.5"
services:
  pgsql:
    image: "postgres:12.6"
    env_file: ./.dockerfiles/postgresql/.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./.dockerfiles/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:5.0.11
    ports:
      - "6379:6379"
  sidekiq-ui:
    build:
      context: .dockerfiles/sidekiq-ui/
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    expose:
      - "9292"
    ports:
      - "9292:9292"
